# theme: jekyll-theme-cayman
copyright: "Copyright by immccn123"
title: immccn123的个人站
lang: zh-cn
nav:
  - name: Home
    link: /
  - name: Blog
    link: /blog.html

links:
  - name: Xrcluogu
    d: xrcluogu
    describe: None
    url: http://github.com/xrcluogu
    headimg: https://avatars.githubusercontent.com/u/81732554