# theme: jekyll-theme-cayman
copyright: 本站所有内容均使用 CC-BY-NC-SA 4.0 协议进行授权。署名：immccn123
title: immccn123's blog
lang: zh-cn
nav:
  - name: Home
    link: https://immccn123.xyz
  - name: Blog
    link: /
  - name: Posts
    link: /blog.html
  - name: Projects and Documents
    link: /projects.html


